### ISSUE TITLE
梯度问题

### ISSUE THREAD

**Issue by zhangxin-516** [INVOKERer/AdaRevD#20]
Traceback (most recent call last):
  File "basicsr/train.py", line 332, in <module>
    main()
  File "basicsr/train.py", line 286, in main
    model.optimize_parameters(current_iter) 
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/image_restoration_model.py", line 165, in optimize_parameters
    l_pix.backward()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/decoder_test.py", line 162, in backward
    torch.autograd.backward(oup2, g2_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/encoder_test.py", line 134, in backward
    torch.autograd.backward(oup3, g3_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 1956 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.
您在使用可逆结构的时候出现过这种问题吗。我把整个网络改成了可逆的结构，使用4张3090—24的训练，就出现了这种问题

**Comment by INVOKERer** [comment]
将TORCH_DISTRIBUTED_DEBUG加到sh里应该可以看到具体报错，CUDA_VISIBLE_DEVICES=0,1,2,3 TORCH_DISTRIBUTED_DEBUG python ...

**Comment by zhangxin-516** [comment]
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [48, 3, 1, 1], strides() = [3, 1, 3, 3]
bucket_view.sizes() = [48, 3, 1, 1], strides() = [3, 1, 1, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "basicsr/train.py", line 332, in <module>
    main()
  File "basicsr/train.py", line 286, in main
    model.optimize_parameters(current_iter) 
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/image_restoration_model.py", line 165, in optimize_parameters
    l_pix.backward()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/decoder_test.py", line 162, in backward
    torch.autograd.backward(oup2, g2_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/encoder_test.py", line 134, in backward
    torch.autograd.backward(oup3, g3_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 1956 with name subnet3.level3.blocks.1.ffn.att.SpatialGate.layer4.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [48, 3, 1, 1], strides() = [3, 1, 3, 3]
bucket_view.sizes() = [48, 3, 1, 1], strides() = [3, 1, 1, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [48, 3, 1, 1], strides() = [3, 1, 3, 3]
bucket_view.sizes() = [48, 3, 1, 1], strides() = [3, 1, 1, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [48, 3, 1, 1], strides() = [3, 1, 3, 3]
bucket_view.sizes() = [48, 3, 1, 1], strides() = [3, 1, 1, 1] (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/torch/csrc/distributed/c10d/reducer.cpp:312.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "basicsr/train.py", line 332, in <module>
    main()
  File "basicsr/train.py", line 286, in main
    model.optimize_parameters(current_iter) 
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/image_restoration_model.py", line 165, in optimize_parameters
    l_pix.backward()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/decoder_test.py", line 162, in backward
    torch.autograd.backward(oup2, g2_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/encoder_test.py", line 134, in backward
    torch.autograd.backward(oup3, g3_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 1956 with name subnet3.level3.blocks.1.ffn.att.SpatialGate.layer4.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
Traceback (most recent call last):
  File "basicsr/train.py", line 332, in <module>
    main()
  File "basicsr/train.py", line 286, in main
    model.optimize_parameters(current_iter) 
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/image_restoration_model.py", line 165, in optimize_parameters
    l_pix.backward()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/decoder_test.py", line 162, in backward
    torch.autograd.backward(oup2, g2_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/encoder_test.py", line 134, in backward
    torch.autograd.backward(oup3, g3_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 1956 with name subnet3.level3.blocks.1.ffn.att.SpatialGate.layer4.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
Traceback (most recent call last):
  File "basicsr/train.py", line 332, in <module>
    main()
  File "basicsr/train.py", line 286, in main
    model.optimize_parameters(current_iter) 
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/image_restoration_model.py", line 165, in optimize_parameters
    l_pix.backward()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/decoder_test.py", line 162, in backward
    torch.autograd.backward(oup2, g2_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/archs/modules/encoder_test.py", line 134, in backward
    torch.autograd.backward(oup3, g3_up, retain_graph=True)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 1956 with name subnet3.level3.blocks.1.ffn.att.SpatialGate.layer4.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1705) of binary: /root/miniconda3/envs/py38/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
basicsr/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-10_14:58:16
  host      : autodl-container-b7b443bad6-0b9763c1
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1706)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-10_14:58:16
  host      : autodl-container-b7b443bad6-0b9763c1
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1707)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-10_14:58:16
  host      : autodl-container-b7b443bad6-0b9763c1
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1708)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-10_14:58:16
  host      : autodl-container-b7b443bad6-0b9763c1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1705)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================这是输出的内容。您遇到过吗

**Comment by INVOKERer** [comment]
这种一般是代码写得有问题，错误点在subnet3.level3.blocks.1.ffn.att.SpatialGate.layer4.weight has been marked as ready twice.

**Comment by zhangxin-516** [comment]
您的解码器部分使用了可逆的结构，使用类似torch.autograd.backward(oup3, g3_up, retain_graph=True) 的语句，出现过参数被标记多次的问题吗。非常感谢您回答我以上的问题

**Comment by INVOKERer** [comment]
这样的问题在我写代码的时候经常会遇到，基本都是有部分代码写错导致的，你可以仔细检查下，或者你可以先把save_memory设置为False检查模型是否可以正常训练。

**Comment by zhangxin-516** [comment]
作者您好，我想问一下，我的代码在单卡上是可以运行的，但是再多卡上就会出现损失函数上升直至nan，请问您遇到过这个问题吗

**Comment by INVOKERer** [comment]
可以先将lr调小点试试，nan值的出现一般和网络架构或模块不合理相关，也和学习率等其它参数设置不合理有关系。

**Comment by zhangxin-516** [comment]
不好意思再次打扰您，我昨天晚上中断了我的程序，今天早上想要重新运行，但是出来了这个错误：Traceback (most recent call last):
  File "basicsr/train.py", line 332, in <module>
    main()
  File "basicsr/train.py", line 286, in main
    model.optimize_parameters(current_iter).cuda(GPU) 
  File "/root/autodl-tmp/LoFormer-main/basicsr/models/image_restoration_model.py", line 168, in optimize_parameters
    self.optimizer_g.step()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/adamw.py", line 161, in step
    adamw(params_with_grad,
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/adamw.py", line 218, in adamw
    func(params,
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/optim/adamw.py", line 259, in _single_tensor_adamw
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 70573) of binary: /root/miniconda3/envs/py38/bin/python

**Comment by INVOKERer** [comment]
这个问题遇到过，但是我忘了具体是怎么解决的。可以试试从别的地方复制一个新的state或者把最新的state删除。有问题可以加我微信mxt97-0410。
