### ISSUE TITLE
Thank you for your outstanding work. I encountered this problem during testing and I don’t quite understand the cause. Could you please help me find out how to solve it? IndexError: index 4 is out of range

### ISSUE THREAD

**Issue by sudonghao** [INVOKERer/AdaRevD#21]
torch.Size([4, 64, 384, 384]) torch.Size([4, 128, 192, 192]) torch.Size([4, 256, 96, 96]) torch.Size([4, 512, 48, 48]) torch.Size([4, 1024, 24, 24])
  0%|                                                                                                                                                                            | 0/5 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/notebook/code/personal/91090388/AdaRevD-master/val.py", line 139, in <module>
    restored, num_decoders = model_restoration(input_)
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 184, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/notebook/code/personal/91090388/AdaRevD-master/basicsr/models/archs/AdaRevID_arch.py", line 1473, in forward
    out_parts = self.forward_feature(features)
  File "/home/notebook/code/personal/91090388/AdaRevD-master/basicsr/models/archs/AdaRevID_arch.py", line 1485, in forward_feature
    return self._forward_pretrain(features)
  File "/home/notebook/code/personal/91090388/AdaRevD-master/basicsr/models/archs/AdaRevID_arch.py", line 1667, in _forward_pretrain
    e3, e2, e1, e0 = self.subdenets[i](e4, e3, e2, e1, e0)
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/modules/container.py", line 297, in __getitem__
    return self._modules[self._get_abs_string_index(idx)]
  File "/opt/conda/envs/NAF/lib/python3.10/site-packages/torch/nn/modules/container.py", line 287, in _get_abs_string_index
    raise IndexError(f'index {idx} is out of range')

**Comment by INVOKERer** [comment]
Hi, maybe you can check the baseblock, the decoder_idx  and exit_idx in the yml. Make sure that decoder_idx == len(baseblock) and the number in exit_idx <= len(baseblock).

**Comment by sudonghao** [comment]
Thank you very much for your advice
