### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by git-guocc** [INVOKERer/AdaRevD#3]
basicsr/models/archs/UFPNet_code_uncertainty_arch.py，作者，您好！你这个文件是不是放错文件夹了，我直接默认运行会报错ModuleNotFoundErrorModuleNotFoundError: : No module named 'basicsr.models.archs.UFPNet_code_uncertainty_arch'No module named 'basicsr.models.archs.UFPNet_code_uncertainty_arch'

**Comment by INVOKERer** [comment]
额，是哪个py文件报的错？在AdaRevD.py里应该是basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch。这个项目我没怎么整理就上传了，可能还有些bug。。。

**Comment by git-guocc** [comment]
cd AdaRevD
./train_4gpu.sh Motion_Deblurring/Options/GoPro-AdaRevIDB-pretrain-4gpu.yml就是默认执行这个，
![image](https://github.com/INVOKERer/AdaRevD/assets/81276451/65f33b42-d96d-40b1-96eb-b203491866f3这个位置有问题
这个是整个错误：
(AdaRevD) ➜  AdaRevD git:(master) ✗ ./train_4gpu.sh Motion_Deblurring/Options/GoPro-AdaRevIDB-pretrain-4gpu.yml
/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "basicsr/train.py", line 13, in <module>
    from basicsr.models import create_model
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 15, in <module>
    _model_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/image_restoration_model.py", line 8, in <module>
    from basicsr.models.archs import define_network
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 15, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/AdaRevID_arch.py", line 17, in <module>
    from basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch import UFPNet, UFPNetLocal
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 21, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 22, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'basicsr.models.archs.UFPNet_code_uncertainty_arch'
Traceback (most recent call last):
  File "basicsr/train.py", line 13, in <module>
    from basicsr.models import create_model
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 15, in <module>
    _model_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/image_restoration_model.py", line 8, in <module>
    from basicsr.models.archs import define_network
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 15, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/AdaRevID_arch.py", line 17, in <module>
    from basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch import UFPNet, UFPNetLocal
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 21, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 22, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'basicsr.models.archs.UFPNet_code_uncertainty_arch'
Traceback (most recent call last):
  File "basicsr/train.py", line 13, in <module>
    from basicsr.models import create_model
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 15, in <module>
    _model_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/image_restoration_model.py", line 8, in <module>
    from basicsr.models.archs import define_network
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 15, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/AdaRevID_arch.py", line 17, in <module>
    from basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch import UFPNet, UFPNetLocal
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 21, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 22, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'basicsr.models.archs.UFPNet_code_uncertainty_arch'
Traceback (most recent call last):
  File "basicsr/train.py", line 13, in <module>
    from basicsr.models import create_model
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 15, in <module>
    _model_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/image_restoration_model.py", line 8, in <module>
    from basicsr.models.archs import define_network
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 15, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/__init__.py", line 16, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/AdaRevID_arch.py", line 17, in <module>
    from basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch import UFPNet, UFPNetLocal
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 21, in <module>
    _arch_modules = [
  File "/home/guocc/GitHub/workshop/News/AdaRevD/basicsr/models/archs/UFPNet/__init__.py", line 22, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'basicsr.models.archs.UFPNet_code_uncertainty_arch'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1943654) of binary: /home/guocc/envs/anaconda3/envs/AdaRevD/bin/python
Traceback (most recent call last):
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/guocc/envs/anaconda3/envs/AdaRevD/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
basicsr/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-25_18:17:08
  host      : guocc-2080ti
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1943655)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-05-25_18:17:08
  host      : guocc-2080ti
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1943656)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-05-25_18:17:08
  host      : guocc-2080ti
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1943657)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-25_18:17:08
  host      : guocc-2080ti
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1943654)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by INVOKERer** [comment]
哦，我之前把basicsr.models.archs.UFPNet_code_uncertainty_arch，没想到训练会有影响，把basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch.py复制一份到basicsr.models.archs.UFPNet_code_uncertainty_arch.py应该就行了。

**Comment by git-guocc** [comment]
对的

**Comment by git-guocc** [comment]
作者，您好！能讲一下这个数据怎么来的吗？我看有py文件有下载数据的，然后，这个_crops是怎么得到的，也是有py执行的吗？可以方便告知一下吗？感谢！&nbsp; &nbsp; dataroot_gt: /data/mxt_data/GoPro/train/target_crops
&nbsp; &nbsp; dataroot_lq: /data/mxt_data/GoPro/train/input_crops





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月25日(星期六) 晚上6:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [INVOKERer/AdaRevD] 环境问题 (Issue #3)














 
哦，我之前把basicsr.models.archs.UFPNet_code_uncertainty_arch，没想到训练会有影响，把basicsr.models.archs.UFPNet.UFPNet_code_uncertainty_arch.py复制一份到basicsr.models.archs.UFPNet_code_uncertainty_arch.py应该就行了。

**Comment by INVOKERer** [comment]
可以参考[Motion_Deblurring
/generate_patches_gopro.py](https://github.com/INVOKERer/DeepRFT/blob/AAAI2023/Motion_Deblurring/generate_patches_gopro.py)
